server:
    port: 8080
    contextPath: /bxfw
spring:
    profiles:
        active: local
    datasource:
        secret-file: /etc/secret-dev.properties
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    redis:
        host: 123.57.185.91
        port: 6379
        password: 45b339c0ad5fccc574a20567e9fd9ff5
        timeout: 100000
        maxTotal: 300
        maxIdle: 100
        maxWaitMillis: 1000*100
        testOnBorrow: true
logging:
    config: classpath:config/logback-prod.xml
lifeinsurancesystem:
    bxfw:
        bxfwSys: pro
        ossImgUrl: http://www.sxfwxt.com/bxfw-pro
        